// https://github.com/ttaubert/x-server-js
// (c) 2013 Tim Taubert <tim@timtaubert.de>
// x-server.js may be freely distributed under the MIT license.

"use strict";

var ATOMS = [
  null,
  // 1-5
  "PRIMARY", "SECONDARY", "ARC", "ATOM", "BITMAP",
  // 6-10
  "CARDINAL", "COLORMAP", "CURSOR", "CUT_BUFFER0", "CUT_BUFFER1",
  // 11-15
  "CUT_BUFFER2", "CUT_BUFFER3", "CUT_BUFFER4", "CUT_BUFFER5", "CUT_BUFFER6",
  // 16-20
  "CUT_BUFFER7", "DRAWABLE", "FONT", "INTEGER", "PIXMAP",
  // 21-25
  "POINT", "RECTANGLE", "RESOURCE_MANAGER", "RGB_COLOR_MAP", "RGB_BEST_MAP",
  // 26-30
  "RGB_BLUE_MAP", "RGB_DEFAULT_MAP", "RGB_GRAY_MAP", "RGB_GREEN_MAP", "RGB_RED_MAP",
  // 31-35
  "STRING", "VISUALID", "WINDOW", "WM_COMMAND", "WM_HINTS",
  // 36-40
  "WM_CLIENT_MACHINE", "WM_ICON_NAME", "WM_ICON_SIZE", "WM_NAME", "WM_NORMAL_HINTS",
  // 41-45
  "WM_SIZE_HINTS", "WM_ZOOM_HINTS", "MIN_SPACE", "NORM_SPACE", "MAX_SPACE",
  // 46-50
  "END_SPACE", "SUPERSCRIPT_X", "SUPERSCRIPT_Y", "SUBSCRIPT_X", "SUBSCRIPT_Y",
  // 51-55
  "UNDERLINE_POSITION", "UNDERLINE_THICKNESS", "STRIKEOUT_ASCENT", "STRIKEOUT_DESCENT", "ITALIC_ANGLE",
  // 56-60
  "X_HEIGHT", "QUAD_WIDTH", "WEIGHT", "POINT_SIZE", "RESOLUTION",
  // 61-65
  "COPYRIGHT", "NOTICE", "FONT_NAME", "FAMILY_NAME", "FULL_NAME",
  // 66-68
  "CAP_HEIGHT", "WM_CLASS", "WM_TRANSIENT_FOR",
];

module.exports = {
  atoms: ATOMS
};
